Run cd kernel-source
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
Using .config as base
Merging arch/arm64/configs/vendor/tucana.config
Value of CONFIG_CSID_CAMERA is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_CSID_CAMERA is not set
New value: CONFIG_CSID_CAMERA=y
Value of CONFIG_SOFTLED_CAMERA is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_SOFTLED_CAMERA is not set
New value: CONFIG_SOFTLED_CAMERA=y
Value of CONFIG_MACH_XIAOMI_TUCANA is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_MACH_XIAOMI_TUCANA is not set
New value: CONFIG_MACH_XIAOMI_TUCANA=y
Value of CONFIG_INPUT_FINGERPRINT is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_INPUT_FINGERPRINT is not set
New value: CONFIG_INPUT_FINGERPRINT=y
Value of CONFIG_INPUT_DRV260X_HAPTICS is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_INPUT_DRV260X_HAPTICS is not set
New value: CONFIG_INPUT_DRV260X_HAPTICS=y
Value of CONFIG_LEDS_QPNP_HAPTICS is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: CONFIG_LEDS_QPNP_HAPTICS=y
New value: # CONFIG_LEDS_QPNP_HAPTICS is not set
Value of CONFIG_LEDS_QPNP_VIBRATOR_LDO is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: CONFIG_LEDS_QPNP_VIBRATOR_LDO=y
New value: # CONFIG_LEDS_QPNP_VIBRATOR_LDO is not set
Value of CONFIG_RC_CORE is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_RC_CORE is not set
New value: CONFIG_RC_CORE=y
Value of CONFIG_LEDS_AW3644 is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_LEDS_AW3644 is not set
New value: CONFIG_LEDS_AW3644=y
Value of CONFIG_BATT_VERIFY_BY_DS28E16 is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_BATT_VERIFY_BY_DS28E16 is not set
New value: CONFIG_BATT_VERIFY_BY_DS28E16=y
Value of CONFIG_BQ2597X_CHARGE_PUMP is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_BQ2597X_CHARGE_PUMP is not set
New value: CONFIG_BQ2597X_CHARGE_PUMP=y
Value of CONFIG_ONEWIRE_GPIO is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: # CONFIG_ONEWIRE_GPIO is not set
New value: CONFIG_ONEWIRE_GPIO=y
Value of CONFIG_SMB1355_SLAVE_CHARGER is redefined by fragment arch/arm64/configs/vendor/tucana.config:
Previous value: CONFIG_SMB1355_SLAVE_CHARGER=y
New value: # CONFIG_SMB1355_SLAVE_CHARGER is not set
  CC      scripts/mod/empty.o
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/mod/mk_elfconfig
  HOSTCC  scripts/dtc/flattree.o
  CC      scripts/mod/devicetable-offsets.s
  MKELF   scripts/mod/elfconfig.h
  CHK     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/selinux/mdp/mdp
  UPD     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/sumversion.o
  SHIPPED scripts/genksyms/parse.tab.c
  SHIPPED scripts/genksyms/lex.lex.c
  SHIPPED scripts/genksyms/parse.tab.h
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/pnmtologo
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/dtc/util.o
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/sortextable
  HOSTLD  scripts/mod/modpost
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/sign-file
  HOSTCC  scripts/extract-cert
  HOSTLD  scripts/dtc/dtc
========================================================
🚨 НАСТОЯЩАЯ ОШИБКА СБОРКИ (СКОПИРУЙ МНЕ ЭТОТ ТЕКСТ) 🚨
========================================================
========================================================
Error: Process completed with exit code 1.
